const WORDS = [
    { word: "JAVASCRIPT", definition: "Programming language for web interactivity", category: "Technology" },
    { word: "KEYBOARD", definition: "Input device with keys for typing", category: "Technology" },
    { word: "DEVELOPER", definition: "A person who writes software", category: "Technology" },
    { word: "ALGORITHM", definition: "Step-by-step procedure to solve a problem", category: "Technology" },
    { word: "DATABASE", definition: "Organized collection of structured data", category: "Technology" },
    { word: "FRAMEWORK", definition: "Reusable structure that helps build software faster", category: "Technology" },
    { word: "RESPONSIVE", definition: "Design that adapts to different screen sizes", category: "Technology" },
    { word: "FUNCTION", definition: "Reusable block of code that performs a task", category: "Technology" },
    { word: "VARIABLE", definition: "Named container that stores a value", category: "Technology" },
    { word: "BROWSER", definition: "Software used to access the internet", category: "Technology" },
    { word: "NETWORK", definition: "Group of connected computers", category: "Technology" },
    { word: "INTERFACE", definition: "Point of interaction between user and system", category: "Technology" },
    { word: "COMPILER", definition: "Program that translates code into machine language", category: "Technology" },
    { word: "DEBUGGING", definition: "Process of finding and fixing errors in code", category: "Technology" },
    { word: "ENCRYPTION", definition: "Converting data into a secret code", category: "Technology" },
    { word: "FIREWALL", definition: "Security system that monitors network traffic", category: "Technology" },
    { word: "HARDWARE", definition: "Physical components of a computer", category: "Technology" },
    { word: "SOFTWARE", definition: "Programs and operating information of a computer", category: "Technology" },
    { word: "PROTOCOL", definition: "Set of rules governing data communication", category: "Technology" },
    { word: "RECURSION", definition: "Function that calls itself to solve a problem", category: "Technology" },
    { word: "ITERATION", definition: "Repeating a process multiple times", category: "Technology" },
    { word: "BOOLEAN", definition: "Data type with only true or false values", category: "Technology" },
    { word: "SYNTAX", definition: "Rules that define the structure of a language", category: "Technology" },
    { word: "RUNTIME", definition: "Period when a program is executing", category: "Technology" },
    { word: "BACKEND", definition: "Server-side of a web application", category: "Technology" },
    { word: "FRONTEND", definition: "Client-side of a web application", category: "Technology" },
    { word: "CACHE", definition: "Temporary storage for fast data access", category: "Technology" },
    { word: "PIXEL", definition: "Smallest unit of a digital image", category: "Technology" },
    { word: "BANDWIDTH", definition: "Maximum rate of data transfer in a network", category: "Technology" },
    { word: "REPOSITORY", definition: "Storage location for software project files", category: "Technology" },
    { word: "DEPLOYMENT", definition: "Process of releasing software to users", category: "Technology" },
    { word: "BLOCKCHAIN", definition: "Distributed ledger technology for secure records", category: "Technology" },
    { word: "VIRTUAL", definition: "Existing in a computer environment", category: "Technology" },

    { word: "ELEPHANT", definition: "Largest land animal with a trunk", category: "Animals" },
    { word: "DOLPHIN", definition: "Intelligent marine mammal known for playfulness", category: "Animals" },
    { word: "PENGUIN", definition: "Flightless bird that lives in cold climates", category: "Animals" },
    { word: "GIRAFFE", definition: "Tallest living terrestrial animal", category: "Animals" },
    { word: "CHEETAH", definition: "Fastest land animal on earth", category: "Animals" },
    { word: "GORILLA", definition: "Largest living primate", category: "Animals" },
    { word: "CROCODILE", definition: "Large reptile that lives near water", category: "Animals" },
    { word: "FLAMINGO", definition: "Pink wading bird that stands on one leg", category: "Animals" },
    { word: "CHAMELEON", definition: "Lizard that can change its skin color", category: "Animals" },
    { word: "PLATYPUS", definition: "Egg-laying mammal with a duck bill", category: "Animals" },
    { word: "JAGUAR", definition: "Large wild cat native to the Americas", category: "Animals" },
    { word: "OCTOPUS", definition: "Eight-armed sea creature with soft body", category: "Animals" },
    { word: "PARROT", definition: "Colorful bird known for mimicking speech", category: "Animals" },
    { word: "SCORPION", definition: "Arachnid with a venomous stinger tail", category: "Animals" },
    { word: "WOLVERINE", definition: "Fierce solitary mammal of cold regions", category: "Animals" },
    { word: "NARWHAL", definition: "Arctic whale with a long spiral tusk", category: "Animals" },
    { word: "CAPYBARA", definition: "Largest rodent in the world", category: "Animals" },
    { word: "AXOLOTL", definition: "Mexican salamander that can regrow limbs", category: "Animals" },
    { word: "MEERKAT", definition: "Small mongoose that stands upright to watch for danger", category: "Animals" },
    { word: "PIRANHA", definition: "Freshwater fish with sharp teeth", category: "Animals" },
    { word: "TOUCAN", definition: "Tropical bird with a large colorful beak", category: "Animals" },
    { word: "WALRUS", definition: "Large marine mammal with long tusks", category: "Animals" },
    { word: "PANTHER", definition: "Black leopard or jaguar", category: "Animals" },
    { word: "STINGRAY", definition: "Flat fish with a venomous tail", category: "Animals" },
    { word: "ARMADILLO", definition: "Mammal with a protective bony shell", category: "Animals" },
    { word: "MONGOOSE", definition: "Small carnivore known for fighting snakes", category: "Animals" },
    { word: "VOLCANO", definition: "Mountain that can erupt with lava", category: "Nature" },
    { word: "MOUNTAIN", definition: "Large natural elevation of earth", category: "Nature" },
    { word: "GLACIER", definition: "Slow-moving mass of ice", category: "Nature" },
    { word: "TORNADO", definition: "Violently rotating column of air", category: "Nature" },
    { word: "TSUNAMI", definition: "Large ocean wave caused by earthquake", category: "Nature" },
    { word: "AVALANCHE", definition: "Rapid flow of snow down a mountainside", category: "Nature" },
    { word: "HURRICANE", definition: "Tropical storm with violent winds", category: "Nature" },
    { word: "LIGHTNING", definition: "Flash of light caused by electric discharge", category: "Nature" },
    { word: "WATERFALL", definition: "Cascade of water falling from a height", category: "Nature" },
    { word: "CANYON", definition: "Deep gorge carved by a river", category: "Nature" },
    { word: "DESERT", definition: "Dry barren land with little rain", category: "Nature" },
    { word: "JUNGLE", definition: "Dense tropical forest", category: "Nature" },
    { word: "TUNDRA", definition: "Treeless arctic plain", category: "Nature" },
    { word: "GEYSER", definition: "Hot spring that erupts water and steam", category: "Nature" },
    { word: "LAGOON", definition: "Shallow body of water near the sea", category: "Nature" },
    { word: "MONSOON", definition: "Seasonal wind bringing heavy rainfall", category: "Nature" },
    { word: "SAVANNA", definition: "Flat grassland in tropical regions", category: "Nature" },
    { word: "BLIZZARD", definition: "Severe snowstorm with strong winds", category: "Nature" },
    { word: "ECLIPSE", definition: "Blocking of light from one celestial body by another", category: "Nature" },
    { word: "EROSION", definition: "Gradual wearing away of land by water or wind", category: "Nature" },
    { word: "FOSSIL", definition: "Preserved remains of ancient organisms", category: "Nature" },
    { word: "RAPIDS", definition: "Fast-flowing turbulent section of a river", category: "Nature" },
    { word: "STALACTITE", definition: "Rock formation hanging from a cave ceiling", category: "Nature" },
    { word: "TRIBUTARY", definition: "Stream that flows into a larger river", category: "Nature" },

    { word: "UNIVERSE", definition: "All existing matter, space and time", category: "Science" },
    { word: "GRAVITY", definition: "Force that attracts objects toward each other", category: "Science" },
    { word: "TELESCOPE", definition: "Instrument used to observe distant objects", category: "Science" },
    { word: "PHOTOSYNTHESIS", definition: "Process plants use to convert sunlight into food", category: "Science" },
    { word: "HIBERNATION", definition: "State of inactivity animals enter in winter", category: "Science" },
    { word: "CONSTELLATION", definition: "Group of stars forming a pattern in the sky", category: "Science" },
    { word: "METAMORPHOSIS", definition: "Process of transformation from one form to another", category: "Science" },
    { word: "ATMOSPHERE", definition: "Layer of gases surrounding a planet", category: "Science" },
    { word: "MOLECULE", definition: "Smallest unit of a chemical compound", category: "Science" },
    { word: "NEUTRON", definition: "Neutral particle found in atomic nucleus", category: "Science" },
    { word: "ELECTRON", definition: "Negatively charged particle orbiting nucleus", category: "Science" },
    { word: "CHROMOSOME", definition: "Structure carrying genetic information", category: "Science" },
    { word: "EVOLUTION", definition: "Gradual development of species over time", category: "Science" },
    { word: "HYPOTHESIS", definition: "Proposed explanation for an observation", category: "Science" },
    { word: "LABORATORY", definition: "Room equipped for scientific experiments", category: "Science" },
    { word: "MAGNETISM", definition: "Force of attraction between magnetic objects", category: "Science" },
    { word: "NUCLEUS", definition: "Central part of an atom or cell", category: "Science" },
    { word: "RADIATION", definition: "Energy transmitted as waves or particles", category: "Science" },
    { word: "VELOCITY", definition: "Speed of an object in a given direction", category: "Science" },
    { word: "OSMOSIS", definition: "Movement of water through a membrane", category: "Science" },
    { word: "CATALYST", definition: "Substance that speeds up a chemical reaction", category: "Science" },
    { word: "DIFFUSION", definition: "Spreading of particles from high to low concentration", category: "Science" },
    { word: "ENZYME", definition: "Protein that speeds up biological reactions", category: "Science" },
    { word: "FRICTION", definition: "Resistance force between two surfaces", category: "Science" },
    { word: "INERTIA", definition: "Tendency of an object to resist change in motion", category: "Science" },
    { word: "MOMENTUM", definition: "Quantity of motion of a moving body", category: "Science" },

    { word: "DEMOCRACY", definition: "System of government by the people", category: "Society" },
    { word: "PHILOSOPHY", definition: "Study of fundamental questions about existence", category: "Society" },
    { word: "ECONOMY", definition: "System of production and consumption of goods", category: "Society" },
    { word: "JUSTICE", definition: "Fair treatment according to the law", category: "Society" },
    { word: "PARLIAMENT", definition: "Legislative body of a government", category: "Society" },
    { word: "REVOLUTION", definition: "Overthrow of a government or social order", category: "Society" },
    { word: "COMMUNITY", definition: "Group of people living in the same area", category: "Society" },
    { word: "CONSTITUTION", definition: "Fundamental principles of a nation", category: "Society" },
    { word: "MIGRATION", definition: "Movement of people from one place to another", category: "Society" },
    { word: "PROPAGANDA", definition: "Information used to promote a political cause", category: "Society" },
    { word: "SOVEREIGNTY", definition: "Supreme authority of a state", category: "Society" },
    { word: "TRADITION", definition: "Customs passed down through generations", category: "Society" },
    { word: "DIPLOMACY", definition: "Management of relations between nations", category: "Society" },
    { word: "IDEOLOGY", definition: "System of ideas forming a political belief", category: "Society" },
    { word: "LEGISLATION", definition: "Laws enacted by a governing body", category: "Society" },

    { word: "SYMPHONY", definition: "Long musical composition for orchestra", category: "Arts" },
    { word: "SCULPTURE", definition: "Three-dimensional work of art", category: "Arts" },
    { word: "PORTRAIT", definition: "Painting or photo of a person", category: "Arts" },
    { word: "ORCHESTRA", definition: "Large group of musicians playing together", category: "Arts" },
    { word: "LITERATURE", definition: "Written works with artistic value", category: "Arts" },
    { word: "MELODY", definition: "Sequence of musical notes forming a tune", category: "Arts" },
    { word: "CANVAS", definition: "Surface used for painting", category: "Arts" },
    { word: "GALLERY", definition: "Room or building for displaying art", category: "Arts" },
    { word: "NOVEL", definition: "Long fictional narrative in book form", category: "Arts" },
    { word: "POETRY", definition: "Literary work using rhythmic language", category: "Arts" },
    { word: "THEATER", definition: "Place where plays are performed", category: "Arts" },
    { word: "BALLET", definition: "Classical form of dance with precise movements", category: "Arts" },
    { word: "DOCUMENTARY", definition: "Film that presents factual information", category: "Arts" },
    { word: "OPERA", definition: "Dramatic work combining singing and music", category: "Arts" },
    { word: "SATIRE", definition: "Use of humor to criticize something", category: "Arts" },
    { word: "TYPOGRAPHY", definition: "Art of arranging type for visual appeal", category: "Arts" },

    { word: "PYRAMID", definition: "Ancient structure with triangular sides", category: "History" },
    { word: "GLADIATOR", definition: "Roman warrior who fought in arenas", category: "History" },
    { word: "PHARAOH", definition: "Ruler of ancient Egypt", category: "History" },
    { word: "COLOSSEUM", definition: "Ancient Roman amphitheater", category: "History" },
    { word: "FEUDALISM", definition: "Medieval system of land ownership", category: "History" },
    { word: "RENAISSANCE", definition: "Period of cultural rebirth in Europe", category: "History" },
    { word: "CRUSADE", definition: "Medieval military expedition to the Holy Land", category: "History" },
    { word: "DYNASTY", definition: "Series of rulers from the same family", category: "History" },
    { word: "INQUISITION", definition: "Historical Catholic investigation of heresy", category: "History" },
    { word: "MONARCHY", definition: "Government ruled by a king or queen", category: "History" },
    { word: "PLAGUE", definition: "Deadly epidemic disease", category: "History" },
    { word: "SLAVERY", definition: "System where people are owned as property", category: "History" },
    { word: "TREATY", definition: "Formal agreement between nations", category: "History" },
    { word: "VIKING", definition: "Norse seafarer and warrior of the Middle Ages", category: "History" },
    { word: "CIVILIZATION", definition: "Advanced stage of human social development", category: "History" },

    { word: "LABYRINTH", definition: "Complicated network of passages", category: "Places" },
    { word: "CATHEDRAL", definition: "Large important Christian church", category: "Places" },
    { word: "PENINSULA", definition: "Land almost surrounded by water", category: "Places" },
    { word: "ARCHIPELAGO", definition: "Group of islands", category: "Places" },
    { word: "METROPOLIS", definition: "Large important city", category: "Places" },
    { word: "SANCTUARY", definition: "Place of safety or refuge", category: "Places" },
    { word: "OASIS", definition: "Fertile spot in a desert with water", category: "Places" },
    { word: "HARBOR", definition: "Sheltered body of water for ships", category: "Places" },
    { word: "FORTRESS", definition: "Military stronghold", category: "Places" },
    { word: "DUNGEON", definition: "Underground prison in a castle", category: "Places" },
    { word: "MONASTERY", definition: "Building where monks live and work", category: "Places" },
    { word: "OBSERVATORY", definition: "Building for studying celestial objects", category: "Places" },
    { word: "PLATEAU", definition: "Flat elevated area of land", category: "Places" },
    { word: "VALLEY", definition: "Low area between hills or mountains", category: "Places" },
    { word: "WILDERNESS", definition: "Uncultivated land in its natural state", category: "Places" },

    { word: "VACCINE", definition: "Substance used to stimulate immunity", category: "Health" },
    { word: "EPIDEMIC", definition: "Widespread occurrence of a disease", category: "Health" },
    { word: "DIAGNOSIS", definition: "Identification of a disease from symptoms", category: "Health" },
    { word: "THERAPY", definition: "Treatment for physical or mental disorder", category: "Health" },
    { word: "ANATOMY", definition: "Study of the structure of living things", category: "Health" },
    { word: "BACTERIA", definition: "Single-celled microorganisms", category: "Health" },
    { word: "GENETICS", definition: "Study of heredity and genes", category: "Health" },
    { word: "IMMUNITY", definition: "Ability to resist a particular infection", category: "Health" },
    { word: "METABOLISM", definition: "Chemical processes that occur in living organisms", category: "Health" },
    { word: "PANDEMIC", definition: "Disease outbreak spread across countries", category: "Health" },
    { word: "PROTEIN", definition: "Essential nutrient for building body tissue", category: "Health" },
    { word: "SYMPTOM", definition: "Sign that indicates a disease or condition", category: "Health" },
    { word: "TRANSPLANT", definition: "Transfer of an organ from one body to another", category: "Health" },
    { word: "VITAMIN", definition: "Organic compound essential for health", category: "Health" },
    { word: "NUTRITION", definition: "Process of providing food for growth", category: "Health" },

    { word: "MARATHON", definition: "Long-distance running race of 42 kilometers", category: "Sports" },
    { word: "CHAMPION", definition: "Winner of a competition", category: "Sports" },
    { word: "TOURNAMENT", definition: "Series of contests to determine an overall winner", category: "Sports" },
    { word: "ATHLETE", definition: "Person trained in physical exercise and competition", category: "Sports" },
    { word: "BASKETBALL", definition: "Sport played with a ball through a high hoop", category: "Sports" },
    { word: "GYMNASTICS", definition: "Sport involving exercises requiring balance and agility", category: "Sports" },
    { word: "ARCHERY", definition: "Sport of shooting arrows at a target", category: "Sports" },
    { word: "BOXING", definition: "Combat sport using fists with padded gloves", category: "Sports" },
    { word: "FENCING", definition: "Sport of fighting with swords", category: "Sports" },
    { word: "SURFING", definition: "Sport of riding ocean waves on a board", category: "Sports" },
    { word: "WRESTLING", definition: "Combat sport involving grappling techniques", category: "Sports" },
    { word: "VOLLEYBALL", definition: "Sport played by hitting a ball over a net", category: "Sports" },
    { word: "BADMINTON", definition: "Racket sport played with a shuttlecock over a net", category: "Sports" },
    { word: "TRIATHLON", definition: "Race combining swimming, cycling, and running", category: "Sports" },

    { word: "ADVENTURE", definition: "Exciting or unusual experience", category: "General" },
    { word: "AMBITION", definition: "Strong desire to achieve something", category: "General" },
    { word: "CHALLENGE", definition: "Difficult task that tests your ability", category: "General" },
    { word: "COURAGE", definition: "Ability to do something despite fear", category: "General" },
    { word: "CURIOSITY", definition: "Desire to learn or know about something", category: "General" },
    { word: "DISCOVERY", definition: "Finding something for the first time", category: "General" },
    { word: "ENTHUSIASM", definition: "Intense enjoyment or interest in something", category: "General" },
    { word: "FREEDOM", definition: "Power to act or speak without restraint", category: "General" },
    { word: "HARMONY", definition: "State of being in agreement or concord", category: "General" },
    { word: "IMAGINATION", definition: "Ability to form new ideas or images mentally", category: "General" },
    { word: "KNOWLEDGE", definition: "Facts and information acquired through experience", category: "General" },
    { word: "LEADERSHIP", definition: "Ability to guide and inspire others", category: "General" },
    { word: "MYSTERY", definition: "Something that is difficult to understand", category: "General" },
    { word: "PATIENCE", definition: "Ability to wait calmly without complaint", category: "General" },
    { word: "PERSEVERANCE", definition: "Continued effort despite difficulty", category: "General" },
    { word: "RESILIENCE", definition: "Ability to recover from difficulties", category: "General" },
    { word: "STRATEGY", definition: "Plan of action to achieve a goal", category: "General" },
    { word: "TEAMWORK", definition: "Cooperative effort by a group of people", category: "General" },
    { word: "WISDOM", definition: "Quality of having experience and good judgment", category: "General" }
];

function getRandomWord() {
    const index = Math.floor(Math.random() * WORDS.length);
    return WORDS[index];
}
